// <auto-generated />
using System;
using DbFirstSchool;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbFirstSchool.Migrations
{
    [DbContext(typeof(schoolDBContext))]
    partial class schoolDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("DbFirstSchool.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClassID");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("MaxStudents")
                        .HasColumnType("int");

                    b.HasKey("ClassId");

                    b.ToTable("Class", (string)null);
                });

            modelBuilder.Entity("DbFirstSchool.School", b =>
                {
                    b.Property<int>("SchoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SchoolID");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("SchoolId");

                    b.ToTable("School", (string)null);
                });

            modelBuilder.Entity("DbFirstSchool.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<int?>("SchoolId")
                        .HasColumnType("int")
                        .HasColumnName("SchoolID");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("StudentId");

                    b.HasIndex(new[] { "SchoolId" }, "SchoolID");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("DbFirstSchool.StudentClass", b =>
                {
                    b.Property<int>("ListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ListID");

                    b.Property<int?>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("ClassID");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.HasKey("ListId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ClassId" }, "ClassID");

                    b.HasIndex(new[] { "StudentId" }, "StudentID");

                    b.ToTable("StudentClass", (string)null);
                });

            modelBuilder.Entity("DbFirstSchool.Student", b =>
                {
                    b.HasOne("DbFirstSchool.School", "School")
                        .WithMany("Students")
                        .HasForeignKey("SchoolId")
                        .HasConstraintName("student_ibfk_1");

                    b.Navigation("School");
                });

            modelBuilder.Entity("DbFirstSchool.StudentClass", b =>
                {
                    b.HasOne("DbFirstSchool.Class", "Class")
                        .WithMany("StudentClasses")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("studentclass_ibfk_2");

                    b.HasOne("DbFirstSchool.Student", "Student")
                        .WithMany("StudentClasses")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("studentclass_ibfk_1");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DbFirstSchool.Class", b =>
                {
                    b.Navigation("StudentClasses");
                });

            modelBuilder.Entity("DbFirstSchool.School", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("DbFirstSchool.Student", b =>
                {
                    b.Navigation("StudentClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
